spring.application.name=interview-test

# DATABASE 
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=israel
spring.datasource.password=israel
spring.datasource.driver-class-name=org.h2.Driver




spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


app.jwt.secret=IsraelDanBobadillaSegundoMartes2026
app.jwt.expiration-ms=360000